# Generated by Django 5.2.4 on 2025-07-28 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('libelle', models.CharField(max_length=50)),
                ('quantite', models.IntegerField()),
                ('description', models.TextField()),
                ('date_expirations', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_debut', models.DateField()),
                ('categorie', models.CharField(choices=[('MED', 'Matériel Médical'), ('CHIR', 'Matériel Chirurgical'), ('PHAR', 'Produit Pharmaceutique'), ('BIO', 'Produit Biologique'), ('EQP', 'Equippement Bureautique')], default='PHAR', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EntreProduits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('libelle', models.CharField(max_length=50)),
                ('quantite', models.IntegerField()),
                ('description', models.TextField()),
                ('date_expirations', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_debut', models.DateField()),
                ('categorie', models.CharField(max_length=50)),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.produits')),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_produits', models.IntegerField()),
                ('quantite_sortie', models.IntegerField(default=0)),
                ('quantite_entre', models.IntegerField(default=0)),
                ('categorie', models.CharField(max_length=50)),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock.produits')),
            ],
        ),
    ]
