# Generated by Django 5.2.4 on 2025-07-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_produits_seuil'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreproduits',
            name='seuil',
            field=models.IntegerField(default=4),
        ),
    ]
