# Generated by Django 5.2.4 on 2025-07-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_entreproduits_seuil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreproduits',
            name='quantite',
        ),
        migrations.AddField(
            model_name='entreproduits',
            name='quantite_entre',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produits',
            name='quantite_entre',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produits',
            name='quantite',
            field=models.IntegerField(default=0),
        ),
    ]
