# Generated by Django 5.2.4 on 2025-08-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_entreproduits_quantite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='date_sortie',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
