# Generated by Django 5.2.4 on 2025-08-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_commandeitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='stock',
        ),
    ]
