# Generated by Django 5.2.4 on 2025-08-06 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_remove_commande_quantite_remove_commande_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreproduits',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='entreproduits',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='entreproduits',
            name='date_expirations',
        ),
        migrations.RemoveField(
            model_name='entreproduits',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='entreproduits',
            name='description',
        ),
        migrations.RemoveField(
            model_name='entreproduits',
            name='libelle',
        ),
        migrations.RemoveField(
            model_name='entreproduits',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='entreproduits',
            name='seuil',
        ),
    ]
