# Generated by Django 5.2.4 on 2025-08-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_remove_entreproduits_categorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='categorie',
            field=models.CharField(choices=[('MED', 'Matériel Médical'), ('CHIR', 'Matériel Chirurgical'), ('PHAR', 'Produit Pharmaceutique'), ('BIO', 'Produit Biologique'), ('EQP', 'Equippement Bureautique'), ('LAB', 'Matériel de Laboratoire'), ('HYG', 'Produits d’Hygiène'), ('AMB', 'Matériel Ambulatoire'), ('STK', 'Stock Général'), ('DNT', 'Matériel Dentaire')], default='PHAR', max_length=10),
        ),
    ]
