# Generated by Django 5.2.4 on 2025-08-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='statut',
            field=models.CharField(choices=[('disponible', 'disponible'), ('indisponible', 'indisponible')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='role',
            field=models.CharField(choices=[('Admin', 'Administrateur'), ('User', 'utilisateur')], default='Client', max_length=50),
        ),
    ]
