# Generated by Django 5.2.4 on 2025-08-05 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_utilisateurs_image_utilisateurs_statut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateurs',
            name='statut',
        ),
    ]
