# Generated by Django 5.2.4 on 2025-08-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_remove_utilisateurs_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurs',
            name='Poste',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
