# Generated by Django 5.2.4 on 2025-08-07 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_utilisateurs_poste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateurs',
            old_name='Poste',
            new_name='poste',
        ),
    ]
